import { type Metadata } from 'next'
import { ClerkProvider } from '@clerk/nextjs'
import { Roboto } from 'next/font/google'
import '@/app/globals.css'

const roboto = Roboto({
    weight: ['100', '300', '400', '500', '700', '900'],
    subsets: ['latin'],
    variable: '--font-roboto',
})

export const metadata: Metadata = {
    title: 'ChatGPT',
    description: 'Generated by ys7',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <ClerkProvider>
            <html lang="en">
                <body className={`${roboto.variable} antialiased font-sans`}>
                    {children}
                </body>
            </html>
        </ClerkProvider>
    )
}